version: "2"

services:
  bigartm:
    build: 
        context: .
        dockerfile: bigartm/Dockerfile
    volumes:
      - ${SOURCES_PATH}:/notebooks
      - ./jupyter_notebook_config.json:/home/jovyan/.jupyter/jupyter_notebook_config.json
    ports:
      - 8888:8888
    restart: always